"""Auto-generated by scripts/install_integration.py — do not edit by hand.

Call register_catalog_integrations(mcp) from mcp_server.py after telemetry
and core tools are wired up. To install an integration, run:
    python scripts/install_integration.py <slug>
To remove one, delete its block below and the runtime file in tools/integrations/.
"""
from __future__ import annotations

from typing import Any


def register_catalog_integrations(mcp: Any) -> None:

    # BEGIN integration: decisions
    from tools.integrations import decisions as _decisions_tools  # noqa: PLC0415
    _decisions_tools.register(mcp)
    # END integration: decisions
